{% set name = "rogue" %}
{% set version = "v5.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: 742e9813f0ce403db2aa7d6e5e72b70deb02dd85773b6cae92b0015e4308a0da 

build:
  skip: True  # [win or osx]
  number: 1

requirements:
   build:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
   host:
     - python
     - boost
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - numpy
   run:
     - python
     - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x')}}
     - boost
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - numpy
     - ipython
     - p4p        [linux]
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - pyqt
     - pyepics    [linux]
     - sqlalchemy
     - pydm
     - pyserial

about:
  home: https://github.com/slaclab/rogue
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SLAC Python Based Hardware Abstraction & Data Acquisition System'
  description: |
    python-based hardware abstraction and data acquisition system
    for SLAC.
  doc_url: https://slaclab.github.io/rogue/
  dev_url: https://github.com/slaclab/rogue

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
