{% set name = "rogue" %}
{% set version = "v6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ./rogue-6.1.1.tar.gz
  sha256: c0762d850608dbef04c1c26337b0d7172f1d58849c7f6a529b854a0794bddcff

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER',0) }}

requirements:
   build:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
   host:
     - python=3.9
     - boost
     - bzip2
     - zeromq
     - numpy
   run:
     - python=3.9
     - boost
     - bzip2
     - zeromq
     - numpy
     - ipython
     - p4p
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - sqlalchemy
     - pydm>=1.18.0
     - pyserial
     - matplotlib

about:
  home: https://github.com/slaclab/rogue
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SLAC Python Based Hardware Abstraction & Data Acquisition System'
  description: |
    python-based hardware abstraction and data acquisition system
    for SLAC.
  doc_url: https://slaclab.github.io/rogue/
  dev_url: https://github.com/slaclab/rogue

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
